#!/usr/bin/env python
# Code taken from https://stackoverflow.com/questions/15142134/slides-with-columns-in-pandoc

import pandocfilters as pf

def latex(s):
    return pf.RawBlock('latex', s)

def mk_columns(k, v, f, m):
    if k == "Para":
        value = pf.stringify(v)
        if value.startswith('[') and value.endswith(']'):
            content = value[1:-1]
            if content == "columns<":
                return latex(r'\begin{columns}')
            elif content == ">columns":
                return latex(r'\end{columns}')
            elif content.startswith("column="):
                return latex(r'\column{%s\textwidth}' % content[7:])
            elif content == "$<":
                return latex(r'\begin{adjustwidth}{1cm}{1cm}')
            elif content == ">$":
                return latex(r'\end{adjustwidth}')
            elif content == "code<":
                return latex(r'\begin{spacing}{0.80}')
            elif content == ">code":
                return latex(r'\end{spacing}')

if __name__ == "__main__":
    pf.toJSONFilter(mk_columns)

